# Site settings
title: 타이틀
email: fpshtmxm36@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "/Jekyll_Portfolio" # the base hostname & protocol for your site

github_username: fpshtmxm36
linkedin_username: fpshtmxm36

# Build settings
markdown: kramdown
