# Site settings
title: 타이틀
email:
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/Jekyll_Portfolio" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username: fpshtmxm36
github_username: fpshtmxm36
linkedin_username: fpshtmxm36

# Build settings
markdown: kramdown
